[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)sx24
autorestart=true
priority=1

[program:fluxbox]
command=/home/ubuntu/.fluxbox/startup
environment=DISPLAY=":99"
autorestart=true
user=ubuntu
priority=2

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -shared -rfbport 5900 -nopw -noxdamage
autorestart=true
priority=3

[program:novnc]
command=/opt/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 8080
autorestart=true
priority=4

[program:forge]
command=/opt/bin/start-forge.sh
environment=DISPLAY=":99"
autorestart=unexpected
startretries=5
startsecs=15
user=ubuntu
priority=5
stdout_logfile=/var/log/supervisor/forge.log
stderr_logfile=/var/log/supervisor/forge_err.log
